import { AnalysisRepository } from "../../repository/analysisRepository";
import { sanitizeAnalysisForPersistence } from "../sanitizer";

export async function runPrivacyTests() {
  console.log("Starting Privacy-First Backend Lifecycle Tests...\n");

  const rawConversationData = "너는 왜 매번 피해? 우리 이대로 끝날까봐 무서워. 그만하자.";
  const mockMessageId = "m000001";

  // Mock Analysis Payload generated by AI
  const mockAiOutput = {
    rawConversation: rawConversationData, // Danger! Should be caught
    text: rawConversationData, // Danger!
    originalText: rawConversationData, // Danger!
    signals: {
      AV02: { v: 2, e: [mockMessageId] },
    },
    extracted_data: {
      trigger_phrases: [rawConversationData] // Legacy raw quotes
    },
    dimensions: {
      anxiety: { score: 60, status: "ok" },
      avoidance: { score: 70, status: "ok" }
    },
    fitness: { secure: 10, preoccupied: 40, dismissing: 80, fearful: 30 },
    primary_type: "dismissing",
    premium_report: {
      behavior_patterns: [
        {
          signal_id: "AV02",
          score: 2,
          observation: "갈등 상황에서 대화 철수"
        }
      ]
    },
    access: { premium_unlocked: false }
  };

  let testPassed = true;

  console.log("==================================================");
  console.log("[TEST A & C] DB/API 저장 객체에 실제 대화 quote 제거 (Defensive Validation)");
  try {
    sanitizeAnalysisForPersistence(mockAiOutput);
    console.log("❌ FAIL: Sanitizer failed to throw error when rawConversation is present.");
    testPassed = false;
  } catch (e: any) {
    if (e.message.includes("Defensive Validation Failed")) {
      console.log("✅ PASS: Sanitizer properly threw an error and blocked persistent storage.");
    } else {
      console.log("❌ FAIL: Unexpected error thrown:", e.message);
      testPassed = false;
    }
  }

  console.log("\n==================================================");
  console.log("[TEST B] Remove forbidden keys and test sanitization layer");
  // Remove forbidden keys manually to test the rest of the sanitizer
  const safeOutput = { ...mockAiOutput };
  delete safeOutput.rawConversation;
  delete safeOutput.text;
  delete safeOutput.originalText;

  const sanitized = sanitizeAnalysisForPersistence(safeOutput);
  
  if (sanitized.signals.AV02.e) {
    console.log("❌ FAIL: Message IDs were not stripped from persistent payload.");
    testPassed = false;
  } else if (sanitized.extracted_data.trigger_phrases) {
    console.log("❌ FAIL: Legacy raw quotes were not stripped from persistent payload.");
    testPassed = false;
  } else {
    console.log("✅ PASS: Message IDs and raw quotes successfully stripped.");
  }
  
  const stringified = JSON.stringify(sanitized);
  if (stringified.includes("그만하자") || stringified.includes("매번 피해")) {
    console.log("❌ FAIL: Raw text found in serialized payload!");
    testPassed = false;
  } else {
    console.log("✅ PASS: No raw text found in serialized payload.");
  }


  console.log("\n==================================================");
  console.log("[TEST D & F] Premium Data Access Control");
  
  // We'll test the repository logic using dummy mode.
  // By default dummy returns unlocked: false, but we can mock the DB response logic locally 
  // just by calling the private mapper method for testing.
  
  // Expose the private method for testing purpose only:
  const mapDbRow = (AnalysisRepository as any)._mapDbRowToResult;
  
  const dbRowLocked = {
    id: "test-id",
    premium_unlocked: false,
    premium_report: { secret: "data" }
  };

  const resultLocked = mapDbRow(dbRowLocked, true);
  if (resultLocked.premium_report) {
    console.log("❌ FAIL: Premium report leaked when locked!");
    testPassed = false;
  } else {
    console.log("✅ PASS: Premium report is NOT returned when locked.");
  }

  const dbRowUnlocked = {
    id: "test-id",
    premium_unlocked: true,
    premium_report: { secret: "data" }
  };

  const resultUnlocked = mapDbRow(dbRowUnlocked, true);
  if (!resultUnlocked.premium_report || resultUnlocked.premium_report.secret !== "data") {
    console.log("❌ FAIL: Premium report was missing even though it was unlocked.");
    testPassed = false;
  } else {
    console.log("✅ PASS: Premium report successfully returned when unlocked.");
  }

  console.log("\n==================================================");
  console.log("[TEST E] Public Share API Data Access Control");
  
  const resultPublic = mapDbRow(dbRowUnlocked, false); // isOwner = false
  if (resultPublic.premium_report) {
    console.log("❌ FAIL: Premium report leaked in public share API!");
    testPassed = false;
  } else {
    console.log("✅ PASS: Premium report successfully hidden from public share, even if unlocked.");
  }

  console.log("\n==================================================");
  if (testPassed) {
    console.log("🎉 ALL PRIVACY TESTS PASSED. Raw Conversation Persistence: NONE");
  } else {
    console.log("⚠️ SOME TESTS FAILED.");
  }
}

runPrivacyTests();
